os:
  - linux
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - server # build server branch only
before_install:
  - npm install -g hexo-cli
install:
  - npm install
  - npm install qiniu
script:
  - hexo generate --force # generate static files
after_success:
  - git config --local user.name "niemingzhao"
  - git config --local user.email "1432440963@qq.com"
  - sed -i "s~git@github.com:~https://${GH_TOKEN}@github.com/~" _config.yml
  - hexo deploy > /dev/null
  - node qupload.js ${QN_AK} ${QN_SK} Zone_z0 hexo-site http://www.niemingzhao.top/
